version: '3.8'
services:

  esmaster1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    hostname: esmaster1
    healthcheck:
      test: "curl -s http://localhost:9200/_cluster/health | grep green || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 45s
    ports:
      - 9200:9200
    environment:
      - node.name=esmaster1
      - node.roles=master
      - cluster.name=${ELASTIC_CLUSTER_NAME}
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - discovery.seed_hosts=esmaster2,esmaster3
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - reindex.remote.whitelist=${ELK_WHITELIST}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - network.publish_host=esmaster1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.labels.jacs_name==node1 ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ${DATA_DIR}/elasticsearch/master:/usr/share/elasticsearch/data
    networks:
      - jacs-es-net

  esmaster2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    hostname: esmaster2
    healthcheck:
      test: "curl -s http://localhost:9200/_cluster/health | grep green || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 45s
    ports:
      - 9201:9200
    environment:
      - node.name=esmaster2
      - node.roles=master
      - cluster.name=${ELASTIC_CLUSTER_NAME}
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - discovery.seed_hosts=esmaster1,esmaster3
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - reindex.remote.whitelist=${ELK_WHITELIST}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - network.publish_host=esmaster2
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.labels.jacs_name==node2 ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ${DATA_DIR}/elasticsearch/master:/usr/share/elasticsearch/data
    networks:
      - jacs-es-net

  esmaster3:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    ports:
      - 9202:9200
    environment:
      - node.name=esmaster3
      - node.roles=master
      - cluster.name=${ELASTIC_CLUSTER_NAME}
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - discovery.seed_hosts=esmaster1,esmaster2
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - reindex.remote.whitelist=${ELK_WHITELIST}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - network.publish_host=esmaster3
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.labels.jacs_name==node3 ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ${DATA_DIR}/elasticsearch/master:/usr/share/elasticsearch/data
    networks:
      - jacs-es-net

  esdata1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.name=esdata1
      - node.roles=data
      - cluster.name=${ELASTIC_CLUSTER_NAME}
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - discovery.seed_hosts=esmaster1,esmaster2,esmaster3
      - "ES_JAVA_OPTS=-Xms24g -Xmx24g"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.labels.jacs_name==node1 ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ${DATA_DIR}/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - jacs-es-net

  esdata2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.name=esdata2
      - node.roles=data
      - cluster.name=${ELASTIC_CLUSTER_NAME}
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - discovery.seed_hosts=esmaster1,esmaster2,esmaster3
      - "ES_JAVA_OPTS=-Xms24g -Xmx24g"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.labels.jacs_name==node2 ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ${DATA_DIR}/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - jacs-es-net

  esdata3:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.name=esdata3
      - node.roles=data
      - cluster.name=${ELASTIC_CLUSTER_NAME}
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - discovery.seed_hosts=esmaster1,esmaster2,esmaster3
      - "ES_JAVA_OPTS=-Xms24g -Xmx24g"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.labels.jacs_name==node3 ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ${DATA_DIR}/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - jacs-es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    healthcheck:
      test: curl -fs http://localhost:5601/status || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 90s
    environment:
      - xpack.reporting.kibanaServer.hostname=${HOST1}
      # use host1 for public base URL since we have a placement constraint on node1
      - ELASTICSEARCH_HOSTS=http://esmaster1:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASS}
      - SERVER_PUBLICBASEURL=http://${HOST1}:5601
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ELK_SAVED_OBJECTS_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ELK_REPORTING_KEY}
      - XPACK_SECURITY_ENCRYPTIONKEY=${ELK_SECURITY_KEY}
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.labels.jacs_name==node1 ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ${CONFIG_DIR}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ${DATA_DIR}/elasticsearch/kibana:/usr/share/kibana/data
    depends_on:
      - esmaster1
      - logstash
    networks:
      - jacs-es-net

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    healthcheck:
      test: curl -fs http://localhost:9600 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://esmaster1:9200
      - CONFIG_RELOAD_AUTOMATIC=true
      - "LS_JAVA_OPTS=-Xmx16g -Xms16g"
    volumes:
      - ${CONFIG_DIR}/logstash/pipelines.yml:/usr/share/logstash/pipelines.yml:ro
      - ${CONFIG_DIR}/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 9600:9600
      - 5044:5044
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints: [ node.labels.jacs_name==node1 ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - esmaster1
      - filebeat
    networks:
      - jacs-es-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
    command: filebeat -e -strict.perms=false
    volumes:
     - ${CONFIG_DIR}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
     - filebeat_data:/usr/share/filebeat/data:rw
     - ${CONFIG_DIR}/filebeat/docker/containers:/var/lib/docker/containers:ro
     - /var/run/docker.sock:/var/run/docker.sock
    user: '0:0'
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - jacs-es-net

networks:
  jacs-es-net:
    driver: overlay
    attachable: true

volumes:
  filebeat_data:
