version: "3.0"

networks:
  jacs-net:
    driver: overlay
#    attachable: true

services:
  api-gateway:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  auth-service:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  ipp:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  jacs-async:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  jacs-messaging:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  jacs-sync:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  jade-agent:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  jade-master:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  mongo1:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  mongo2:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  mongo3:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  mysql:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  rabbitmq:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
  solr-search:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.server==extws1]
