version: '3.7'

services:

  jade-master:
    volumes:
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared
      - /nrs/mouselight-v:/nrs/mouselight-v:ro,shared

  jade-agent1:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /groups/scicompsys/reports:/groups/scicompsys/reports:ro,shared
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared
      - /nrs/mouselight-v:/nrs/mouselight-v:ro,shared

  jacs-sync:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared
      - /nrs/mouselight-v:/nrs/mouselight-v:ro,shared

