version: '3.7'

services:

  # Updates containers whenever a new "latest" image is available
  shepherd:
    image: mazzolino/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SLEEP_TIME=2m
    deploy:
      placement:
        constraints: [node.role==manager]

  jade-agent2:
    volumes:
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro,shared
      - /groups/scicomp/lsms:/groups/scicomp/lsms:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared
      - /nrs/mouselight-v:/nrs/mouselight-v:ro,shared

  jade-agent3:
    volumes:
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro,shared
      - /groups/scicomp/lsms:/groups/scicomp/lsms:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared
      - /nrs/mouselight-v:/nrs/mouselight-v:ro,shared

