version: '3.7'
services:

  jade-agent1:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /groups/scicompsys/reports:/groups/scicompsys/reports:ro,shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:shared
      - /groups/flylight:/groups/flylight:ro,shared
      - /groups/projtechres:/groups/projtechres:ro,shared
      - /groups/ditp:/groups/ditp:ro,shared
      - /groups/leet:/groups/leet:ro,shared
      - /groups/lightsheet:/groups/lightsheet:ro,shared
      - /groups/scicomp/lsms:/groups/scicomp/lsms:ro,shared
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared
      - /nrs/svoboda/bakaj/mouselight_data:/nrs/svoboda/bakaj/mouselight_data:ro,shared

  jacs-sync:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:shared

