version: "3.7"

services:

  jade-agent1:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /groups/scicompsys/reports:/groups/scicompsys/reports:ro,shared
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared
      - /nrs/svoboda/bakaj/mouselight_data:/nrs/svoboda/bakaj/mouselight_data:ro,shared
      - /data/s3data:/s3data:shared
      - /nearline/flylight:/nearline/flylight:shared
      - /groups/cellmap:/groups/cellmap:shared
      - /nrs/scicompsoft:/nrs/scicompsoft:shared

  jacs-sync:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared

