version: '3.7'
services:

  jade-agent2:
    image: ${NAMESPACE}/jacs-storage:${JACS_STORAGE_VERSION}
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:shared
      - /groups/flylight:/groups/flylight:ro,shared
      - /groups/projtechres:/groups/projtechres:ro,shared
      - /groups/ditp:/groups/ditp:ro,shared
      - /groups/leet:/groups/leet:ro,shared
      - /groups/lightsheet:/groups/lightsheet:ro,shared
      - /groups/scicomp/lsms:/groups/scicomp/lsms:ro,shared

  jade-agent3:
    image: ${NAMESPACE}/jacs-storage:${JACS_STORAGE_VERSION}
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro,shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:shared
      - /groups/flylight:/groups/flylight:ro,shared
      - /groups/projtechres:/groups/projtechres:ro,shared
      - /groups/ditp:/groups/ditp:ro,shared
      - /groups/leet:/groups/leet:ro,shared
      - /groups/lightsheet:/groups/lightsheet:ro,shared
      - /groups/scicomp/lsms:/groups/scicomp/lsms:ro,shared

