version: "3.7"

services:

  jade-agent1:
    volumes:
      - /groups/scicompsys/reports:/groups/scicompsys/reports:ro,shared
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro,shared
      - /groups/jacs/jacsShare:/groups/jacs/jacsShare:ro,shared
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:shared
      - /groups/flylight:/groups/flylight:ro,shared
      - /groups/projtechres:/groups/projtechres:ro,shared
      - /groups/ditp:/groups/ditp:ro,shared
      - /groups/leet:/groups/leet:ro,shared
      - /groups/lightsheet:/groups/lightsheet:ro,shared
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro,shared
      - /nrs/mouselight:/nrs/mouselight:ro,shared
      - /nrs/svoboda:/nrs/svoboda:ro,shared
      - /data/s3:/data/s3:shared
      - /nearline/flylight:/nearline/flylight:shared
      - /nearline/jacs:/nearline/jacs:shared
      - /groups/cellmap:/groups/cellmap:shared
      - /nrs/scicompsoft:/nrs/scicompsoft:shared
      - /nrs/cellmap:/nrs/cellmap:shared
      - /nrs/lsms:/nrs/lsms:ro,shared
