version: '3.7'

services:

  # Updates containers whenever a new "latest" image is available
  shepherd:
    image: mazzolino/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SLEEP_TIME=2m
    deploy:
      placement:
        constraints: [node.role==manager]

  jade-master:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:ro
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro
      - /nrs/mouselight:/nrs/mouselight:ro

  jade-agent1:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:ro
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro
      - /nrs/mouselight:/nrs/mouselight:ro

  jacs-sync:
    volumes:
      - /groups/scicomp/reports:/groups/scicomp/reports:ro
      - /groups/mousebrainmicro:/groups/mousebrainmicro:ro
      - /groups/jacs/jacsDev:/groups/jacs/jacsDev:ro
      - /nrs/jacs/jacsData:/nrs/jacs/jacsData:ro
      - /nrs/mouselight:/nrs/mouselight:ro

