version: '3.7'

services:

  # Updates containers whenever a new "latest" image is available
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30


