#
# JACS Applications
#
# This service set needs to be composed with the databases defined in docker-compose-db.yml
#

version: '3.7'
services:

  jacs-messaging:
    image: ${NAMESPACE}/jacs-messaging:latest
    user: ${DOCKER_USER}
    depends_on:
      - rabbitmq
      - jacs-sync
    volumes:
      - ${BACKUPS_DIR}/messaging:/app/backup
    environment:
      - SYSTEM_OWNER=group:mouselight
      - RABBITMQ_HOSTNAME=rabbitmq
      - JACS_URL=http://jacs-sync:8080/api/rest-v2/
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    restart: unless-stopped
    networks:
      - jacs-net

  jade-master:
    image: ${NAMESPACE}/jacs-storage:latest
    user: ${DOCKER_USER}
    volumes:
      - ${CONFIG_DIR}/jade:/app/config:ro
      - ${DATA_DIR}:/data
    environment:
      - SERVICE_MODE=master
      - JAVA_OPTS=-Xmx2G -Xms512M -Dlogback.configurationFile=/app/config/logback-master.xml
      - JACSSTORAGE_CONFIG=/app/config/config.properties
      - jade_JWT_SecretKey=${JWT_SECRET_KEY}
      - jade_StorageService_ApiKey=${JADE_API_KEY}
      - jade_MongoDB_ServerName=${MONGODB_SERVER}
      - jade_MongoDB_ReplicaSet=
      - jade_MongoDB_Database=jacs_jade_dev
      - jade_MongoDB_AuthDatabase=admin
      - jade_MongoDB_Username=${MONGODB_APP_USERNAME}
      - jade_MongoDB_Password=${MONGODB_APP_PASSWORD}
    expose:
      - '8080'
    ports:
      - '9880:8080'
    restart: unless-stopped
    networks:
      - jacs-net

  jade-agent1:
    image: ${NAMESPACE}/jacs-storage:latest
    user: ${DOCKER_USER}
    depends_on:
      - jade-master
    volumes:
      - ${CONFIG_DIR}/jade:/app/config:ro
      - ${DATA_DIR}:/data
    environment:
      - SERVICE_MODE=agent
      - JACSSTORAGE_CONFIG=/app/config/config.properties
      - JAVA_OPTS=-Xmx2G -Xms512M -Dlogback.configurationFile=/app/config/logback-agent.xml
      - JADE_MASTER_URL=http://jade-master:8080/jacsstorage/master_api/v1
      - JADE_AGENT_EXPOSED_HOST=${JADE_AGENT_EXPOSED_HOST}
      - JADE_AGENT_EXPOSED_PORT=${JADE_AGENT_EXPOSED_PORT:-9881}
      - jade_JWT_SecretKey=${JWT_SECRET_KEY}
      - jade_StorageService_ApiKey=${JADE_API_KEY}
      - jade_MongoDB_ServerName=${MONGODB_SERVER}
      - jade_MongoDB_ReplicaSet=
      - jade_MongoDB_Database=jacs_jade_dev
      - jade_MongoDB_AuthDatabase=admin
      - jade_MongoDB_Username=${MONGODB_APP_USERNAME}
      - jade_MongoDB_Password=${MONGODB_APP_PASSWORD}
    expose:
      - '8080'
    ports:
      - '${JADE_AGENT_EXPOSED_PORT:-9881}:8080'
    restart: unless-stopped
    networks:
      - jacs-net

  jacs-sync:
    image: ${NAMESPACE}/jacs-compute:latest
    user: ${DOCKER_USER}
    volumes:
      - ${CONFIG_DIR}/jacs-sync:/app/config
    environment:
      - SERVICE_MODE=sync
      - HOSTNAME=jacs-sync
      - JACS2_CONFIG=/app/config/jacs.properties
      - JACS2_SYNCWEB_OPTS=-Dlogback.configurationFile=/app/config/logback.xml
      - jacs_JWT_SecretKey=${JWT_SECRET_KEY}
      - jacs_MongoDB_ServerName=${MONGODB_SERVER}
      - jacs_MongoDB_AuthDatabase=${MONGODB_INIT_DATABASE}
      - jacs_MongoDB_Username=${MONGODB_APP_USERNAME}
      - jacs_MongoDB_Password=${MONGODB_APP_PASSWORD}
      - jacs_Messaging_Server=rabbitmq
      - jacs_Messaging_User=${RABBITMQ_USER}
      - jacs_Messaging_Password=${RABBITMQ_PASSWORD}
      - jacs_mouselight_db_url=${MYSQL_URL}
      - jacs_mouselight_db_user=${MYSQL_JACS_USER}
      - jacs_mouselight_db_password=${MYSQL_JACS_PASSWORD}
      - jacs_StorageService_URL=http://jade-master:8080/jacsstorage/master_api/v1
      - jacs_StorageService_ApiKey=${JADE_API_KEY}
      - jacs_Solr_ServerURL=http://jacs-solr:8080/solr/
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - jacs-net

  jacs-dashboard:
    # Nginx must run as root
    image: ${NAMESPACE}/jacs-dashboard:latest
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - jacs-net

  ipp:
    image: ${NAMESPACE}/ipp:latest
    user: ${DOCKER_USER}
    volumes:
      - ${CONFIG_DIR}/ipp:/app/config
    environment:
      - LIGHTSHEET_INTERFACE_SETTINGS=/app/config/env_config.py
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - jacs-net

  api-gateway:
    # This container must run as root in order to bind to port 443
    image: ${NAMESPACE}/api-gateway:latest
    volumes:
      - ${CONFIG_DIR}/certs:/app/certs:ro
      - ${CONFIG_DIR}/api-gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ${CONFIG_DIR}/api-gateway/content:/usr/local/openresty/nginx/html/external:ro
    environment:
      - JWT_SECRET=${JWT_SECRET_KEY}
    ports:
      - "443:443"
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - jacs-sync
      - jade-master
    restart: unless-stopped
    networks:
      - jacs-net


