version: "3.7"

services:

  # Updates containers whenever a new "latest" image is available
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30

  solr:
    image: ${NAMESPACE}/solr-search:latest

  jacs-messaging:
    image: ${NAMESPACE}/jacs-messaging:latest

  jade-master:
    image: ${NAMESPACE}/jacs-storage:latest

  jade-agent1:
    image: ${NAMESPACE}/jacs-storage:latest

  jacs-sync:
    image: ${NAMESPACE}/jacs-compute:latest

  api-gateway:
    image: ${NAMESPACE}/api-gateway:latest

  jacs-dashboard:
    image: ${NAMESPACE}/jacs-dashboard:latest

  ipp:
    image: ${NAMESPACE}/ipp:latest

  workstation-site:
    image: ${NAMESPACE}/workstation-site:latest


