#
# JACS Applications
#
# This service set needs to be composed with the databases defined in docker-compose-db.yml
#

version: '3'
services:

  auth-service:
    image: registry.int.janelia.org/jacs/auth-service:latest
    user: ${DOCKER_USER}
    volumes:
      - /opt/config/auth-service/config.json:/app/config/config.json:ro
    environment:
      - JWT_SECRET=${JWT_SECRET_KEY}
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - jacs-net

  jacs-messaging:
    image: registry.int.janelia.org/jacs/jacs-messaging:latest
    user: ${DOCKER_USER}
    depends_on:
      - rabbitmq
      - jacs-sync
    volumes:
      - /opt/data/rabbitmq/backup:/app/backup
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - JACS_URL=http://jacs-sync:8080/api/rest-v2/
      - SYSTEM_OWNER=${SYSTEM_OWNER}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    restart: unless-stopped
    networks:
      - jacs-net

  jade-master:
    image: registry.int.janelia.org/jacs/jacs-storage:latest
    user: ${DOCKER_USER}
    depends_on:
      - mongo1
    volumes:
      - /opt/config/jade:/app/config:ro
      - /data:/data
    environment:
      - SERVICE_MODE=master
      - JAVA_OPTS=-Xmx2G -Xms512M -Dlogback.configurationFile=/app/config/logback-master.xml
      - JACSSTORAGE_CONFIG=/app/config/config.properties
      - jade_JWT_SecretKey=${JWT_SECRET_KEY}
      - jade_MongoDB_ServerName=mongo1:27017,mongo2:27017,mongo3:27017
      - jade_MongoDB_AuthDatabase=${MONGODB_INIT_DATABASE}
      - jade_MongoDB_Username=${MONGODB_APP_USERNAME}
      - jade_MongoDB_Password=${MONGODB_APP_PASSWORD}
    expose:
      - '8080'
    ports:
      - '9880:8080'
    restart: unless-stopped
    networks:
      - jacs-net

  jade-agent:
    image: registry.int.janelia.org/jacs/jacs-storage:latest
    user: ${DOCKER_USER}
    depends_on:
      - jade-master
      - mongo1
    volumes:
      - /opt/config/jade:/app/config:ro
      - /data:/data
    environment:
      - SERVICE_MODE=agent
      - JACSSTORAGE_CONFIG=/app/config/config.properties
      - JAVA_OPTS=-Xmx2G -Xms512M -Dlogback.configurationFile=/app/config/logback-agent.xml
      - JADE_MASTER_URL=http://jade-master:8080/jacsstorage/master_api/v1
      - JADE_AGENT_EXPOSED_HOST=${JADE_AGENT_EXPOSED_HOST}
      - JADE_AGENT_EXPOSED_PORT=${JADE_AGENT_EXPOSED_PORT:-9881}
      - jade_JWT_SecretKey=${JWT_SECRET_KEY}
      - jade_MongoDB_ServerName=mongo1:27017,mongo2:27017,mongo3:27017
      - jade_MongoDB_AuthDatabase=${MONGODB_INIT_DATABASE}
      - jade_MongoDB_Username=${MONGODB_APP_USERNAME}
      - jade_MongoDB_Password=${MONGODB_APP_PASSWORD}
    expose:
      - '8080'
    ports:
      - '9881:8080'
    restart: unless-stopped
    networks:
      - jacs-net

  jacs-sync:
    image: registry.int.janelia.org/jacs/jacs-sync:latest
    user: ${DOCKER_USER}
    volumes:
      - /opt/config/jacs-sync:/app/config
    environment:
      - JACS2_CONFIG=/app/config/jacs.properties
      - JACS2_SYNCWEB_OPTS=-Dlogback.configurationFile=/app/config/logback.xml
      - jacs_MongoDB_ServerName=mongo1:27017,mongo2:27017,mongo3:27017
      - jacs_MongoDB_AuthDatabase=${MONGODB_INIT_DATABASE}
      - jacs_MongoDB_Username=${MONGODB_APP_USERNAME}
      - jacs_MongoDB_Password=${MONGODB_APP_PASSWORD}
      - jacs_mouselight_db_user=${MYSQL_JACS_USER}
      - jacs_mouselight_db_password=${MYSQL_ROOT_PASSWORD}
    expose:
      - "8080"
    depends_on:
      - mongo1
    restart: unless-stopped
    networks:
      - jacs-net

  jacs-async:
    image: registry.int.janelia.org/jacs/jacs-async:latest
    user: ${DOCKER_USER}
    volumes:
      - /opt/config/jacs-async:/app/config:ro
      - /data:/data
    environment:
      - HOSTNAME=jacs-async
      - JACS2_CONFIG=/app/config/jacs.properties
      - JACS2_ASYNCWEB_OPTS=-Dlogback.configurationFile=/app/config/logback.xml
      - jacs_MongoDB_ServerName=mongo1:27017,mongo2:27017,mongo3:27017
      - jacs_MongoDB_AuthDatabase=${MONGODB_INIT_DATABASE}
      - jacs_MongoDB_Username=${MONGODB_APP_USERNAME}
      - jacs_MongoDB_Password=${MONGODB_APP_PASSWORD}
      - jacs_service_queue_id=${JACS_QUEUE_ID}
    expose:
      - "8080"
    depends_on:
      - mongo1
    restart: unless-stopped
    networks:
      - jacs-net

  api-gateway:
    # Nginx must run as root
    image: registry.int.janelia.org/jacs/api-gateway:latest
    volumes:
      - /opt/config/certs:/app/certs:ro
      - /opt/config/api-gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - /data/www/workstation:/usr/local/openresty/nginx/html/workstation:ro
      - /data/www/updates:/usr/local/openresty/nginx/html/updates:ro
    environment:
      - JWT_SECRET=${JWT_SECRET_KEY}
    ports:
      - "443:443"
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - auth-service
      - jacs-sync
      - jacs-async
      - jacs-dashboard
      - jade-master
    restart: unless-stopped
    networks:
      - jacs-net

  jacs-dashboard:
    # Nginx must run as root
    image: registry.int.janelia.org/jacs/jacs-dashboard:latest
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - jacs-net

  solr-search:
    image: registry.int.janelia.org/jacs/solr-search:latest
    user: ${DOCKER_USER}
    volumes:
      - /opt/data:/data
    ports:
      - "8890:8080"
    restart: unless-stopped
    networks:
      - jacs-net

  ipp:
    image: registry.int.janelia.org/jacs/ipp:latest
    user: ${DOCKER_USER}
    volumes:
      - /opt/config/ipp:/app/config
    environment:
      - LIGHTSHEET_INTERFACE_SETTINGS=/app/config/env_config.py
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - jacs-net


