version: "3.0"

networks:
  jacs-net:
    driver: overlay
#    attachable: true

services:

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify --ssl --sslcert=/app/certs/cert.crt --sslkey=/app/certs/cert.key
    ports:
      - 9000:9000
    networks:
      - jacs-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - jacs-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  api-gateway:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          memory: 2G
          cpus: "4"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  auth-service:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          memory: 2G
          cpus: "2"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  ipp:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          memory: 4G
          cpus: "4"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  jacs-async:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "4"
          memory: 10G
        reservations:
          memory: 15G
          cpus: "6"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  jacs-messaging:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          memory: 2G
          cpus: "4"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  jacs-sync:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "2"
          memory: 10G
        reservations:
          memory: 15G
          cpus: "4"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  jade-agent:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          memory: 4G
          cpus: "4"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  jade-master:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "4"
          memory: 1G
        reservations:
          memory: 2G
          cpus: "6"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  mongo1:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "4"
          memory: 24G
        reservations:
          memory: 36G
          cpus: "6"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  mongo2:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "4"
          memory: 24G
        reservations:
          memory: 36G
          cpus: "6"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  mongo3:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          memory: 2G
          cpus: "2"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  mysql:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "2"
          memory: 8G
        reservations:
          memory: 12G
          cpus: "4"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  rabbitmq:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          memory: 4G
          cpus: "6"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s

  solr-search:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.extws1==true]
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          memory: 2G
          cpus: "4"
      restart_policy:
        condition: unless-stopped
        delay: 3s
        max_attempts: 3
        window: 120s
