version: '3.7'
services:

  jacs-messaging:
    image: registry.int.janelia.org/jacs/jacs-messaging:1.0.0-extws

  jade-master:
    image: registry.int.janelia.org/jacs/jacs-storage:1.0.0

  jade-agent1:
    image: registry.int.janelia.org/jacs/jacs-storage:1.0.0

  jade-agent2:
    image: registry.int.janelia.org/jacs/jacs-storage:1.0.0

  jacs-sync:
    image: registry.int.janelia.org/jacs/jacs-sync:1.0.0

  jacs-async:
    image: registry.int.janelia.org/jacs/jacs-async:1.0.0

  api-gateway:
    image: registry.int.janelia.org/jacs/api-gateway:1.0.0

