version: "3.7"

networks:
  jacs-net:
    driver: overlay
    attachable: true

services:

  portainer:
    networks:
      - jacs-net
    image: portainer/portainer:1.20.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "1"
          memory: 100M
        reservations:
          cpus: "1"
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  agent:
    networks:
      - jacs-net
    image: portainer/agent:1.2.1
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          cpus: "1"
          memory: 100M
        reservations:
          cpus: "1"
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  mongo1:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.name==node1]
      resources:
        limits:
          cpus: "6"
          memory: 36G
        reservations:
          cpus: "4"
          memory: 24G
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  mongo2:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.name==node2]
      resources:
        limits:
          cpus: "6"
          memory: 36G
        reservations:
          cpus: "4"
          memory: 24G
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  mongo3:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.name==node2]
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  mysql:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.name==node2]
      resources:
        limits:
          cpus: "4"
          memory: 12G
        reservations:
          cpus: "2"
          memory: 8G
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  rabbitmq:
    networks:
      - jacs-net
    deploy:
      placement:
        constraints: [node.labels.name==node1]
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "6"
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

